title: Your Blog Name
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A stylish Jekyll blog starter template.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://your-username.github.io" # your base URL
twitter_username: your_twitter
github_username:  your_github

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Enable drafts (drafts are in _drafts folder and not published)
show_drafts: true

markdown: kramdown
kramdown:
  input: GFM

# Exclude drafts from GitHub Pages build by default
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _drafts